package cn.kungreat.fxgamemap;

public enum ImageObjectType {
    FIXED_BODY,MONSTER,FIXED_ANIMATION,FIXED_BODY_TOP,FIXED_ANIMATION_NM,FIXED_ANIMATION_FOOD,FIXED_MOVE_LR,FIXED_MOVE_TB,FIXED_ANIMATION_STAR;
}
